### ISSUE TITLE
Displaying 'TAKEBACK' and ghost moves

### ISSUE THREAD

**Issue by djdekker** [jromang/picochess#112]
Since I updated Picochess to v0.47 the clock shows "TAKEBACK" during normal play and appears to register ghost moves.

* I'm playing a 5 minute game with White, without rushing the moves: 1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Bc5 5. Be3 Qf6 6. c3
* so far, so good -- the webserver is also following along correctly, showing the correct position and correct moves
* but now... after playing 6. c3 the clock says "TAKEBACK"
* no problem... because I can still see Black's next move on the web server: 6... Ne7
* I carry out Black's move on the board and think about my next move
* now unexpectedly the clock says "Nxd4"
* the webserver now shows the problem: Picochess has somehow replaced my 6. c3 by a ghost move (6. f3) and forgot its own last move 6... Ne7, replacing it by 6... Nxd4.
* when executing 6... Nxd4 Picochess won't continue unless I undo 6. c3 Ne7 and play 6. f3 instead (and the game carries on without further problems).

**Comment by LocutusOfPenguin** [comment]
Hi,
i tried to reproduce this error. Cant. So, i ask y some questions. Please give feedback, and by the way also to the other issues 1xx from you.

1) Can y reproduce this behaviour all the time, or only happened once to you?
2) Did y SLIDE pieces maybe?
3) g8-e7 is a book move..Do y change the opening book at beginning to something else? if yes, which? I get an instant answer, Ne7, and not takeback.
4) What browser & OS y are using to see webserver output? When y play a normal game, is the board and the move list always up-to-date? General question.

=>Yr "no problem" is already one ;-) If y not taking back, shouldn't see this.

Jürgen

**Comment by djdekker** [comment]
1. It happens every now and then. I played a lot of games today without the spurious 'TAKEBACK' message appearing. But then I started the web server and after a couple of games there it was again (video clip https://youtu.be/ssxqnszedcc -- sorry no HD quality). Not sure if the web server has anything to do with it, it could just be a coincidence.
2. No, there was no sliding.
3. Yes, I set the opening book to 'Open' (black queen on d3). 
4. I'm on Raspbian Wheezy from Jonas' image, using the Iceweasel browser. The board and move list are usually up-to-date, but sometimes (not often) they seem to lag behind or get stuck.

Yes, I'm on the 0.47 master branch.

**Comment by djdekker** [comment]
Just now the issue has occurred again, this time not during the opening. After these moves: 1.e4 e5 2.f4 exf4 3.Nf3 Ne7 4.Bc4 d5 5.exd5 Nxd5 6.O-O Be6 7.Bb5+ c6 8.Ba4 Nd7 9.d4 Bd6 10.c4 Ne3 11.Bxe3 fxe3 12.b3 O-O 13.Nc3 Nf6 14.Qd3 Bf4 15.Nd1 b5 16.cxb5 cxb5 17.Bxb5 Nd5 18.Re1 Bg4 I played 19.Nxe3, but Picochess changed that into 19.Kf1 and gave the 'TAKEBACK' message.

**Comment by LocutusOfPenguin** [comment]
weird.

My Problem with all your tickets is:
I'm around 17 commits ahead (and getting more), cause i want to bring out some total new program (at least i have this feeling, haha). Want to merge Fr, Sa...so very soon.

If I'm successful, i can track down errors better, and hopefully alot of them are already solved, hmmm.
Anyway, alot of them not happening to me, like this c3=>f3 stuff. Lets see.

But i have other problems..like server not updating move list or board all the time. But this i have for months...nothing new.

**Comment by djdekker** [comment]
Unfortunately the bug still exists in Picochess 0.48 (master branch).

Starting Picochess without the `-web` option does not solve it. The bug still occurs.

Latest example was already at move 1 (1 min blitz, standard opening book, standard level):
* I play 1. f4
* clock says 'TAKEBACK'
* webserver diagram shows 1. f4 g6
* webserver move list shows 1. g3 d5
* webserver shows "Computer move: d7d5"
* after some time (don't know how long) clock display changes into 'd5'

**Comment by LocutusOfPenguin** [comment]
Its ok...But i wished to know what exactly the problem is ;-)

This morning i also had similar problem. For me , happened when the log saying
"Undoing game until FEN xyz".

Playing f4, in 1min blitz, brings up the error EVERY time, or just sometimes?
If always: can y make sure, y not touch the f3 square?
I guess y using the RASP for it, yes?

**Comment by djdekker** [comment]
If only there were some pattern... The log says nothing when this happens.
The error happens occasionally and unpredictably. Sometimes in the opening, sometimes in the middle game. It can happen with any time control and any opening book. Very frustrating...

Yes, I'm always playing on RasPi2, never on a virtual board. I'll reinstall Pico on a fresh SD card tomorrow and see if the hardware is somehow corrupted.

**Comment by LocutusOfPenguin** [comment]
2015-07-28 07:27:32.931 DEBUG dgthardware - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-07-28 07:27:33.46 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN]
2015-07-28 07:27:33.112 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_TEXT
2015-07-28 07:27:33.117 DEBUG dgthardware - _display_on_dgt_3000: new game
2015-07-28 07:27:33.138 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:33.153 DEBUG dgthardware - process_message: Clock ACK (16, 12, 0, 0)
2015-07-28 07:27:33.158 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:27:33.224 DEBUG dgthardware - run: Read dgt from queue: Dgt.LIGHT_CLEAR
2015-07-28 07:27:34.1 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:35.301 DEBUG dgtdisplay - run: Read message from queue: Message.SYSTEM_INFO
2015-07-28 07:27:45.725 DEBUG picochess - main: Loaded engine [Stockfish 6 64]
2015-07-28 07:27:45.725 DEBUG picochess - main: Supported options [OptionMap({'Clear Hash': Option(name='Clear Hash', type='button', default='', min=None, max=None, var=[]), 'Move Overhead': Option(name='Move Overhead', type='spin', default=30, min=0, max=5000, var=[]), 'Ponder': Option(name='Ponder', type='check', default=True, min=None, max=None, var=[]), 'Syzygy50MoveRule': Option(name='Syzygy50MoveRule', type='check', default=True, min=None, max=None, var=[]), 'SyzygyProbeDepth': Option(name='SyzygyProbeDepth', type='spin', default=1, min=1, max=100, var=[]), 'Min Split Depth': Option(name='Min Split Depth', type='spin', default=0, min=0, max=12, var=[]), 'MultiPV': Option(name='MultiPV', type='spin', default=1, min=1, max=500, var=[]), 'Contempt': Option(name='Contempt', type='spin', default=0, min=-100, max=100, var=[]), 'Slow Mover': Option(name='Slow Mover', type='spin', default=80, min=10, max=1000, var=[]), 'Minimum Thinking Time': Option(name='Minimum Thinking Time', type='spin', default=20, min=0, max=5000, var=[]), 'Write Debug Log': Option(name='Write Debug Log', type='check', default=False, min=None, max=None, var=[]), 'SyzygyProbeLimit': Option(name='SyzygyProbeLimit', type='spin', default=6, min=0, max=6, var=[]), 'UCI_Chess960': Option(name='UCI_Chess960', type='check', default=False, min=None, max=None, var=[]), 'Skill Level': Option(name='Skill Level', type='spin', default=20, min=0, max=20, var=[]), 'Hash': Option(name='Hash', type='spin', default=16, min=1, max=1048576, var=[]), 'Threads': Option(name='Threads', type='spin', default=1, min=1, max=128, var=[]), 'SyzygyPath': Option(name='SyzygyPath', type='string', default='<empty>', min=None, max=None, var=[])})]
2015-07-28 07:27:45.732 DEBUG picochess - main: Starting picochess with DGT board on [/dev/ttyACM0]
2015-07-28 07:27:45.738 DEBUG selector_events - __init__: Using selector: EpollSelector
2015-07-28 07:27:46.801 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:46.811 DEBUG picochess - main: ChessTalker disabled
2015-07-28 07:27:46.812 DEBUG dgthardware - process_message: Clock ACK (16, 11, 0, 0)
2015-07-28 07:27:46.822 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_VERSION]
2015-07-28 07:27:46.870 DEBUG dgtdisplay - run: Read message from queue: Message.UCI_OPTION_LIST
2015-07-28 07:27:46.870 DEBUG dgtdisplay - run: Read message from queue: Message.STARTUP_INFO
2015-07-28 07:27:47.353 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:47.368 DEBUG dgthardware - send_command: ->DGT [Commands.DGT_SEND_VERSION]
2015-07-28 07:27:47.389 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:47.404 DEBUG dgthardware - process_message: Clock version (2, 1)
2015-07-28 07:27:47.410 DEBUG dgthardware - _display_on_dgt_3000: pico 048
2015-07-28 07:27:47.415 DEBUG dgthardware - process_message: Clock ACK (16, 9, 33, 0)
2015-07-28 07:27:47.420 DEBUG dgthardware - send_command: ->DGT [Commands.DGT_SEND_BRD]
2015-07-28 07:27:47.441 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_VERSION], length:2
2015-07-28 07:27:47.461 DEBUG dgthardware - process_message: DGT board version 3.10
2015-07-28 07:27:47.466 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:27:47.547 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:47.573 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BOARD_DUMP], length:64
2015-07-28 07:27:47.588 DEBUG dgthardware - process_message: 
rnbqkbnr
pppppppp
........
........
........
........
PPPPPPPP
RNBQKBNR
2015-07-28 07:27:47.594 DEBUG dgthardware - process_message: Fen
2015-07-28 07:27:47.594 DEBUG picochess - main: Received event in event loop : Event.DGT_FEN
2015-07-28 07:27:47.599 DEBUG dgtdisplay - run: Read message from queue: Message.DGT_FEN
2015-07-28 07:27:47.599 DEBUG dgtdisplay - run: DGT-Fen: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR
2015-07-28 07:27:47.599 DEBUG dgtdisplay - run: New game
2015-07-28 07:27:47.605 DEBUG picochess - main: Received event in event loop : Event.NEW_GAME
2015-07-28 07:27:47.614 INFO uci - stop: Engine already stopped
2015-07-28 07:27:47.614 DEBUG dgtdisplay - run: Read message from queue: Message.STOP_CLOCK
2015-07-28 07:27:47.615 DEBUG dgtdisplay - run: Read message from queue: Message.START_NEW_GAME
2015-07-28 07:27:47.699 DEBUG dgthardware - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-07-28 07:27:47.810 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN]
2015-07-28 07:27:47.873 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_TEXT
2015-07-28 07:27:47.878 DEBUG dgthardware - _display_on_dgt_3000: new game
2015-07-28 07:27:47.989 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:27:48.55 DEBUG dgthardware - run: Read dgt from queue: Dgt.LIGHT_CLEAR
2015-07-28 07:27:48.75 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:48.417 DEBUG dgtdisplay - run: Read message from queue: Message.SYSTEM_INFO
2015-07-28 07:27:48.427 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:48.443 DEBUG dgthardware - process_message: Clock ACK (16, 12, 0, 0)
2015-07-28 07:27:49.341 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:49.357 INFO dgthardware - process_message: dgt clock time received (0, 0, 0) : (12, 8, 8)
2015-07-28 07:27:50.135 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:27:50.948 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:29:53.128 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_FIELD_UPDATE], length:2
2015-07-28 07:29:53.144 DEBUG dgthardware - send_command: ->DGT [Commands.DGT_SEND_BRD]
2015-07-28 07:29:53.170 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_FIELD_UPDATE], length:2
2015-07-28 07:29:53.186 DEBUG dgthardware - send_command: ->DGT [Commands.DGT_SEND_BRD]
2015-07-28 07:29:53.211 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BOARD_DUMP], length:64
2015-07-28 07:29:53.227 DEBUG dgthardware - process_message: 
rnbqkbnr
pppppppp
........
........
.....P..
........
PPPPP.PP
RNBQKBNR
2015-07-28 07:29:53.232 DEBUG dgthardware - process_message: Fen
2015-07-28 07:29:53.248 DEBUG picochess - main: Received event in event loop : Event.DGT_FEN
2015-07-28 07:29:53.253 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BOARD_DUMP], length:64
2015-07-28 07:29:53.253 DEBUG dgtdisplay - run: Read message from queue: Message.DGT_FEN
2015-07-28 07:29:53.254 DEBUG dgtdisplay - run: DGT-Fen: rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR
2015-07-28 07:29:53.254 DEBUG dgtdisplay - run: Evt-Fen: rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR
2015-07-28 07:29:53.259 DEBUG picochess - main: Received event in event loop : Event.FEN
2015-07-28 07:29:53.264 DEBUG picochess - main: Received event in event loop : Event.USER_MOVE
2015-07-28 07:29:53.265 DEBUG dgthardware - process_message: 
rnbqkbnr
pppppppp
........
........
.....P..
........
PPPPP.PP
RNBQKBNR
2015-07-28 07:29:53.270 DEBUG picochess - main: User move [f2f4]
2015-07-28 07:29:53.285 DEBUG dgthardware - process_message: Fen
2015-07-28 07:29:53.303 DEBUG dgtdisplay - run: Read message from queue: Message.STOP_CLOCK
2015-07-28 07:29:53.304 DEBUG picochess - main: Received event in event loop : Event.DGT_FEN
2015-07-28 07:29:53.304 DEBUG dgtdisplay - run: Read message from queue: Message.USER_MOVE
2015-07-28 07:29:53.305 DEBUG picochess - main: Received event in event loop : Event.BEST_MOVE
2015-07-28 07:29:53.305 DEBUG dgtdisplay - run: Read message from queue: Message.RUN_CLOCK
2015-07-28 07:29:53.305 DEBUG dgtdisplay - run: Read message from queue: Message.BOOK_MOVE
2015-07-28 07:29:53.305 DEBUG dgtdisplay - run: Read message from queue: Message.DGT_FEN
2015-07-28 07:29:53.305 DEBUG dgtdisplay - run: DGT-Fen: rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR
2015-07-28 07:29:53.306 DEBUG dgtdisplay - run: Evt-Fen: rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR
2015-07-28 07:29:53.316 DEBUG picochess - main: Received event in event loop : Event.SCORE
2015-07-28 07:29:53.317 DEBUG dgtdisplay - run: Read message from queue: Message.STOP_CLOCK
2015-07-28 07:29:53.317 DEBUG picochess - main: Received event in event loop : Event.FEN
2015-07-28 07:29:53.317 DEBUG dgtdisplay - run: Read message from queue: Message.COMPUTER_MOVE
2015-07-28 07:29:53.319 DEBUG picochess - process_fen: Undoing game until FEN :rnbqkbnr/pppppppp/8/8/5P2/8/PPPPP1PP/RNBQKBNR
2015-07-28 07:29:53.319 DEBUG dgtdisplay - run: Read message from queue: Message.SCORE
2015-07-28 07:29:53.320 INFO uci - stop: Engine already stopped
2015-07-28 07:29:53.334 DEBUG dgtdisplay - run: Read message from queue: Message.USER_TAKE_BACK
2015-07-28 07:29:53.408 DEBUG dgthardware - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-07-28 07:29:53.519 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN]
2015-07-28 07:29:53.585 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_TEXT
2015-07-28 07:29:53.590 DEBUG dgthardware - _display_on_dgt_3000: takeback
2015-07-28 07:29:53.706 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:29:53.771 DEBUG dgthardware - run: Read dgt from queue: Dgt.CLOCK_START
2015-07-28 07:29:53.887 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN]
2015-07-28 07:29:53.953 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_TEXT
2015-07-28 07:29:53.958 DEBUG dgthardware - _display_on_dgt_3000: takeback
2015-07-28 07:29:54.74 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_END]
2015-07-28 07:29:54.140 DEBUG dgthardware - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-07-28 07:29:54.160 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:29:54.176 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:29:54.241 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-07-28 07:29:54.247 DEBUG dgthardware - _display_on_dgt_3000: g6      
2015-07-28 07:29:54.358 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN]
2015-07-28 07:29:54.423 DEBUG dgthardware - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-07-28 07:29:54.539 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:29:54.610 DEBUG dgthardware - run: Read dgt from queue: Dgt.DISPLAY_TEXT
2015-07-28 07:29:54.616 DEBUG dgthardware - _display_on_dgt_3000: takeback
2015-07-28 07:29:54.731 DEBUG dgthardware - send_command: ->DGT [Clock.DGT_CMD_CLOCK_ASCII]
2015-07-28 07:29:54.807 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-07-28 07:29:54.823 DEBUG dgthardware - process_message: Clock ACK (16, 12, 0, 0)
2015-07-28 07:29:56.37 DEBUG dgthardware - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7

**Comment by LocutusOfPenguin** [comment]
I don't think its a hardware problem. That would be too easy for me, ha.

This morning i found out, that if i play f4, start again, and again playing f4 i can provoke this error more often (not 100% of time, but very often). see log file above.

So, there is some light on the horizon.
Do y have a skype account? That would be easier for me to discuss this stuff with you (if y dont mind)

**Comment by djdekker** [comment]
It seems it's happening more and more often here. Still haven't found a 100% certain way to reproduce the error.
My Skype handle is dj.dekker.

**Comment by LocutusOfPenguin** [comment]
cant find you with this handle...Y might try to add me (LocutusOfPenguin).... I tried "djdekker" instead.

**Comment by LocutusOfPenguin** [comment]
updated log file (above). d4, nf6,c4
Engine wants to play c5, but i moved very quickly => takeback error
Do i get an fen from board, when the clock is set?!?

**Comment by djdekker** [comment]
The 0.49 master branch still has the TAKEBACK error. It seems that I found a way to reproduce it.
1. start a new game with standard settings (Stockfish, 5min, user White, comp Black, default level, default opening book)
2. play 1. d4
3. the clock displays Black's answer -- do not carry it out yet!
4. lift any **other** Black piece and put it back on its square -- do not play a move with it!
5. the clock now displays 'TAKEBACK'
6. now carry out Black's answer from step 3
7. Pico has changed White's first move, for example into 1. g3 or 1. Nf3

**Comment by LocutusOfPenguin** [comment]
THX...I'll try that out tomorrow.
Fixing is AFTER the slow-down stuff (and other issues with v49).

All prob. finished this week (no promise - as always)

**Comment by djdekker** [comment]
Thank you Jürgen! With today's commit you have solved the takeback issue.

**Comment by LocutusOfPenguin** [comment]
NP.
But i think, i also fixed #108 #109 #114 and maybe #111 
Can you check for your issues, and maybe close them?

**Comment by djdekker** [comment]
I'll check tonight and close all that I can ;)

**Comment by djdekker** [comment]
Version 0.50 has no more takeback errors!
