### ISSUE TITLE
Level not being picked up by Webserver or games.pgn on reboot

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#208]
Hi,

I've come across an annoying little problem whilst playing PicoChess. On reboot the current time control, level, engine and book are written to the picochess.ini file to be picked up on start-up.

I thought at first that the level wasn't being picked up correctly, but it is. What is happening though, is the level doesn't show on the Webserver or in the games.pgn file, therefore missing in the emailed game too.

I've tested this several times and it's always the same.

For instance, I chose Stockfish level 6, no book, and Fischer 10,5 time control & play a game. I log onto the Webserver during the game and it shows Stockfish level 6. I finish the game and I get an email showing Stockfish level 6.

When I reboot my RPi, and play another game without changing the settings, the Webserver shows I'm playing Stockfish with no level, I finish the game and the email of the game doesn't show the level.

I can still win in both games, so I know the level hasn't changed, but it's not being picked up on reboot by the Webserver or games.pgn.

The quick way around this is to set the level after each reboot, but that shouldn't be required.

Al.

**Comment by LocutusOfPenguin** [comment]
on MY branch i fixed it already

**Comment by ScallyBag** [comment]
Cheers Jurgen, how can I contact you directly?

Al.

**Comment by LocutusOfPenguin** [comment]
sorry, y cant. I'm away from development for 1,5weeks (now).

But y can open any issue, comment, and i get an eMail (just cant read so regularly).
That's the reason, this fix is only at MY branch and not live for all. But y can test if y want.

**Comment by ScallyBag** [comment]
Ok, I've updated Picochess, rebuilt engines (DJ's engine updates) and tried it out. It's a new look Webserver, but it still doesn't show the level after a reboot, nor does the email. 

A new problem has arisen however, I can no longer close picochess or reboot with the 2 queens, it still registers a draw and white and black wins tho.

Al.

**Comment by LocutusOfPenguin** [comment]
Hi Al,
the new problem should be solved now

For "level, email" ...have y used MY(!) branch or the standard one? If y not change yr git root, it wont show up. I dont want to do it on public version, cause i cant test code right now.
MY branch = https://github.com/LocutusOfPenguin/picochess
Jürgen

**Comment by ScallyBag** [comment]
Jurgen,

Yes It suddenly came to me last night whilst in bed trying to sleep. I had entered sudo git pull origin master, what would the command be to try out your code changes at any time?

If I apply your changes will it back out all the changes I applied last night?

I'm also helping out DJ with engine tests at the moment, I'm quite enjoying all this.

Cheers,

Al.

**Comment by ScallyBag** [comment]
Jurgen, the Queen shutdown is fixed,

Thanks

Al.

**Comment by ScallyBag** [comment]
Jurgen, I've created another PicoChess system based on your branch via:
sudo git clone --branch master https://github.com/LocutusOfPenguin/picochess.git
Then updated requirements and built engines. I created a picochess.ini and rebooted.
I ran various tests but the WebServer and games.pgn still doesn't show a level after reboot, sorry

Al.

**Comment by LocutusOfPenguin** [comment]
That is okay.this bugfix isn't included in my branch.

**Comment by ScallyBag** [comment]
Jurgen,

That's what I was thinking, how can I test it then?

Al.

**Comment by LocutusOfPenguin** [comment]
my branch & the jromang branch are now same.
And for me it is working with level => issue solved, no?

**Comment by ScallyBag** [comment]
Jurgen,

Yes it now works, thanks very much.

Having set up a new PicoChess system on your LocutusOfPenguin branch, I was hoping to be able to test your changes before applied live. I'll keep the system updated for next time.

Cheers,

Al.
