### ISSUE TITLE
Picochess stalls on startup

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#94]
On startup Picochess will not respond to first move, it stalls for a couple of minutes before responding. Meanwhile selecting the levels, time controls and books DOES work, it responds normally. See video:

https://youtu.be/MQzuEi4U8-8

I'm on master branch in the video. (So it's not updating, right?)

**Comment by djdekker** [comment]
Happens here, too. Updating to 0.41 solved the issue.

**Comment by ifekali** [comment]
Nope, updating doesn't solve it.

**Comment by ifekali** [comment]
BTW, this bug was not introduced with 0.41, I noticed it months ago ...

**Comment by sshivaji** [comment]
I noticed this issue. Will solve this and a few other stability issues this weekend. Can you reproduce this issue if you change logging to info level?

**Comment by puba** [comment]
ay-ay 1:50 min delay on dgt xl clock

**Comment by ifekali** [comment]
Yes, I can reproduce. With logging on "info" the initial stall is still there.

BTW, we have a new bug introduced with latest version bump, the voices not announce *two* moves after user makes a move, but are silent when pico moves. (See the forums with user reporting it.)

The voices behave normally on stable branch (0.39).

> On 13. jun. 2015, at 04.33, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> I noticed this issue. Will solve this and a few other stability issues this weekend. Can you reproduce this issue if you change logging to info level?

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by sshivaji** [comment]
Initial stall should now be fixed in master. Clock detection logic was
broken.

**Comment by ifekali** [comment]
Nope, it still stalls.

> On 14. jun. 2015, at 03.20, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> Initial stall should now be fixed in master. Clock detection logic was
> broken.

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
Puba reported it fixed too, but I'm guessing he simply got lucky one time. (This happens about once in twenty tries, the stall not being there.) The initial delay (stall) is still there on 0.41 master branch.

However, there is NO stall on stable 0.39 branch, I just checked. But apparently Shiv modified the STABLE branch (with remote play) 12 hours ago. Before that, I'm quite sure the stall was there before latest changes ...



> On 14. jun. 2015, at 03.20, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> Initial stall should now be fixed in master. Clock detection logic was
> broken.

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by ifekali** [comment]
Shiv, you modified STABLE branch (with first Remote play code). Indeed there is no more stall now there (showing 0.39 version still).


> On 14. jun. 2015, at 03.20, Shivkumar Shivaji <notifications@github.com> wrote:
> 
> Initial stall should now be fixed in master. 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment]
for me the stall still exists, and its also there without board (=keyboard mode)

**Comment by ifekali** [comment]
Dang, the stall is indeed back on the stable branch. (0.39) This is weird.

> On 14. jun. 2015, at 13.46, Jürgen Précour <notifications@github.com> wrote:
> 
> for me the stall still exists, and its also there without board (=keyboard mode)
> 
> 

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by sshivaji** [comment]
The stall is due to a threading issue and queue. Will commit fix once I figure out right solution. Yes, the issue is not easy to reproduce due to race condition.

**Comment by sshivaji** [comment]
Ok, fixed this one.

It is NOT a race condition like I assumed. Instead it turns out the geoip
library we used takes a long while to respond and is not reliable. I moved
that code to a thread and used a new library. Master branch should be good
now.

**Comment by puba** [comment]
<a href="http://www.freesmileys.org/smileys.php" title="Smiley"><img src="http://www.freesmileys.org/smileys/smiley-happy110.gif" alt="Smiley" border="0" /></a>
